name: Create Release Branch and PR

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true

jobs:
  create_pr:
    runs-on: ubuntu-latest
    env:
      RELEASE_BRANCH_NAME: release/${{ github.event.inputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.1
      - name: Create and push release branch
        run: |
          git checkout -b ${{ env.RELEASE_BRANCH_NAME }}
          git push origin ${{ env.RELEASE_BRANCH_NAME }}
      - name: Create PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Bump version to ${{ steps.parse_info.outputs.next_version }}',
              head: 'version-bump-${{ steps.parse_info.outputs.next_version }}',
              base: '${{ steps.parse_info.outputs.target_branch }}'
            })
