name: Create Tag and Release

on:
  pull_request:
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run cargo build
      run: cargo build --release
    - name: Upload program
      uses: actions/upload-artifact@v4
      with:
        name: crano-crank
        path: target/release/chrono-crank
        if-no-files-found: error

  create:
    needs:
      - build
    if: startsWith(github.head_ref, 'release/') && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Create a tag string
        id: extract_tag
        run: echo "::set-output name=custom_tag::$(echo '${{ github.event.pull_request.head.ref }}' | sed 's/release\///')"
        shell: bash
      - name: Create a tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          custom_tag: ${{ steps.extract_tag.outputs.custom_tag }}
          tag_prefix:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
      - run: ls -lh
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ github.event.pull_request.body }}
          files: |
            chrono-crank
